name: Metrics - Reactions

on:
  schedule:
    - cron: "0 * * * *"   # 每小时运行一次
  workflow_dispatch:

jobs:
  reactions:
    runs-on: ubuntu-latest
    steps:
      - name: Comment reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
