name: Metrics - Combined
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.combined.svg
          
          # 启用 followers 插件
          plugin_people: yes
          plugin_people_limit: 0
          plugin_people_size: 28
          
          # 启用 reactions 插件
          plugin_reactions: yes
          plugin_reactions_limit: 50
          plugin_reactions_details: percentage
