name: Star lists

on:
  workflow_dispatch:  # 先手动触发测试

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate star list
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          token: ${{ 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 }}  # ✅ 改用 GitHub 自带 token
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit: 2
