name: Star lists

on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate star list
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.svg
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ 正确：使用变量
          base: ""
          plugin_starlists: yes
          plugin_starlists_limit: 2
